### ISSUE TITLE
dist file minifier errors in YUI compressor

### ISSUE THREAD

**Issue by pmcquay** [dequelabs/combobo#22]
This seems to stem from an invalid use (according to YUI) of the "id" keyword. I get the below list of errors on the latest dist file. I am not sure if the line numbers are correct or not.

[ERROR] 301:86:invalid property id

[ERROR] 331:39:missing name after . operator

[ERROR] 332:46:missing name after . operator

[ERROR] 333:45:missing name after . operator

[ERROR] 334:70:missing name after . operator

[ERROR] 345:50:missing name after . operator

[ERROR] 360:29:missing name after . operator

[ERROR] 363:49:missing name after . operator

[ERROR] 374:37:missing name after . operator

[ERROR] 395:48:missing name after . operator

[ERROR] 423:36:missing name after . operator

[ERROR] 425:34:missing name after . operator

[ERROR] 430:34:missing name after . operator

[ERROR] 438:30:missing name after . operator

[ERROR] 446:48:missing name after . operator

[ERROR] 450:38:missing name after . operator

[ERROR] 451:19:syntax error

[ERROR] 452:18:syntax error

[ERROR] 453:18:syntax error

[ERROR] 454:20:syntax error

[ERROR] 455:10:syntax error

[ERROR] 463:30:missing name after . operator

[ERROR] 486:24:missing name after . operator

[ERROR] 487:14:syntax error

[ERROR] 488:18:syntax error

[ERROR] 489:30:missing ; before statement

[ERROR] 491:74:missing ; before statement

[ERROR] 494:19:missing } after property list

[ERROR] 501:24:missing ) in parenthetical

[ERROR] 502:8:syntax error

[ERROR] 503:14:syntax error

[ERROR] 504:18:syntax error

[ERROR] 505:30:missing ; before statement

[ERROR] 506:15:syntax error

[ERROR] 510:9:missing ) after argument list

[ERROR] 511:7:syntax error

[ERROR] 512:14:syntax error

[ERROR] 513:18:syntax error

[ERROR] 514:30:missing ; before statement

[ERROR] 515:15:syntax error

[ERROR] 517:11:syntax error

[ERROR] 519:7:syntax error

[ERROR] 520:14:syntax error

[ERROR] 521:18:syntax error

[ERROR] 522:44:missing ; before statement

[ERROR] 523:20:syntax error

[ERROR] 524:11:syntax error

[ERROR] 526:7:syntax error

[ERROR] 531:24:missing name after . operator

[ERROR] 535:17:invalid return

[ERROR] 551:32:missing name after . operator

[ERROR] 552:7:syntax error

[ERROR] 553:5:syntax error

[ERROR] 554:4:syntax error

[ERROR] 555:9:syntax error

[ERROR] 556:11:syntax error

[ERROR] 557:12:syntax error

[ERROR] 559:7:syntax error

[ERROR] 565:13:invalid return

[ERROR] 566:5:syntax error

[ERROR] 567:4:syntax error

[ERROR] 568:9:syntax error

[ERROR] 569:11:syntax error

[ERROR] 574:125:missing name after . operator

[ERROR] 585:13:invalid return

[ERROR] 586:5:syntax error

[ERROR] 587:4:syntax error

[ERROR] 588:9:syntax error

[ERROR] 589:11:syntax error

[ERROR] 596:13:invalid return

[ERROR] 597:5:syntax error

[ERROR] 598:4:syntax error

[ERROR] 599:9:syntax error

[ERROR] 600:11:syntax error

[ERROR] 609:77:missing name after . operator

[ERROR] 613:13:invalid return

[ERROR] 614:5:syntax error

[ERROR] 615:4:syntax error

[ERROR] 616:9:syntax error

[ERROR] 617:11:syntax error

[ERROR] 618:12:syntax error

[ERROR] 623:7:syntax error

[ERROR] 624:13:invalid return

[ERROR] 625:5:syntax error

[ERROR] 626:4:syntax error

[ERROR] 627:9:syntax error

[ERROR] 628:11:syntax error

[ERROR] 633:15:invalid return

[ERROR] 638:32:missing name after . operator

[ERROR] 681:13:invalid return

[ERROR] 682:5:syntax error

[ERROR] 683:4:syntax error

[ERROR] 684:9:syntax error

[ERROR] 685:11:syntax error

[ERROR] 696:32:missing name after . operator

[ERROR] 697:32:missing name after . operator

[ERROR] 700:13:invalid return

[ERROR] 701:5:syntax error

[ERROR] 702:4:syntax error

[ERROR] 703:9:syntax error

[ERROR] 704:11:syntax error

[ERROR] 710:15:invalid return

[ERROR] 721:15:invalid return

[ERROR] 723:50:missing name after . operator

[ERROR] 734:97:missing name after . operator

[ERROR] 735:40:missing name after . operator

[ERROR] 737:7:missing ) after argument list

[ERROR] 737:8:syntax error

[ERROR] 739:13:invalid return

[ERROR] 740:5:syntax error

[ERROR] 741:4:syntax error

[ERROR] 742:9:syntax error

[ERROR] 743:11:syntax error

[ERROR] 751:32:missing name after . operator

[ERROR] 757:34:missing name after . operator

[ERROR] 761:39:missing name after . operator

[ERROR] 769:13:invalid return

[ERROR] 770:5:syntax error

[ERROR] 771:4:syntax error

[ERROR] 773:9:invalid return

[ERROR] 774:1:syntax error

[ERROR] 785:7:syntax error

[ERROR] 797:8:syntax error

[ERROR] 817:8:syntax error

[ERROR] 986:8:syntax error

[ERROR] 1066:8:syntax error

[ERROR] 1070:552:missing name after . operator

[ERROR] 1070:597:missing : in conditional expression

[ERROR] 1070:760:invalid property id

[ERROR] 1070:843:missing ; before statement

[ERROR] 1070:892:missing ; before statement

[ERROR] 1070:1007:missing name after . operator

[ERROR] 1070:1136:missing name after . operator

[ERROR] 1070:1437:missing name after . operator

[ERROR] 1070:1605:missing name after . operator

[ERROR] 1070:1808:missing name after . operator

[ERROR] 1070:1940:missing name after . operator

[ERROR] 1070:2031:invalid property id

[ERROR] 1070:2058:missing name after . operator

[ERROR] 1070:2922:missing variable name

[ERROR] 1070:3487:missing name after . operator

[ERROR] 1070:7564:missing ; before statement

[ERROR] 1141:86:invalid property id

[ERROR] 1146:33:missing name after . operator

[ERROR] 1151:33:missing name after . operator

[ERROR] 1156:33:missing name after . operator

[ERROR] 1183:86:invalid property id

[ERROR] 1199:35:missing name after . operator

[ERROR] 1288:86:invalid property id

[ERROR] 1293:34:missing name after . operator

[ERROR] 1341:86:invalid property id

[ERROR] 1348:28:missing name after . operator

[ERROR] 1367:86:invalid property id

[ERROR] 1373:43:missing name after . operator

[ERROR] 1383:43:missing name after . operator

[ERROR] 1398:86:invalid property id

[ERROR] 1404:30:missing name after . operator

[ERROR] 1706:34:missing ) after argument list

[ERROR] 1710:34:missing ) after argument list

[ERROR] 3239:30:syntax error

[ERROR] 3241:8:syntax error

[ERROR] 3362:8:syntax error

[ERROR] 3452:8:syntax error

[ERROR] 3463:8:syntax error

[ERROR] 3940:14:missing name after . operator

[ERROR] 3942:2:missing ) in parenthetical

[ERROR] 3959:30:syntax error

[ERROR] 3961:8:syntax error

[ERROR] 4292:64:missing ; before statement

[ERROR] 4292:66:unterminated string literal

[ERROR] 4293:47:syntax error

[ERROR] 4293:65:unterminated string literal

[ERROR] 4294:47:syntax error

[ERROR] 4294:57:illegal character

[ERROR] 4294:69:missing ; before statement

[ERROR] 4396:60:unterminated regular expression literal

[ERROR] 4397:4:syntax error

[ERROR] 4414:9:missing ) after argument list

[ERROR] 4414:22:missing ; before statement

[ERROR] 4554:8:syntax error

[ERROR] 4744:8:syntax error

[ERROR] 4755:8:syntax error

[ERROR] 4784:8:syntax error

[ERROR] 4815:8:syntax error

[ERROR] 4826:86:invalid property id

[ERROR] 4872:30:missing name after . operator

[ERROR] 4874:30:missing name after . operator

[ERROR] 4880:8:syntax error

[ERROR] 4920:8:syntax error

[ERROR] 4940:8:syntax error

[ERROR] 4970:8:syntax error

[ERROR] 4971:11:syntax error

[ERROR] 4972:2:syntax error

[ERROR] 4972:3:missing } after function body

[ERROR] 4972:3:missing } after function body

[ERROR] 4972:3:missing } after function body

[ERROR] 1:0:Compilation produced 196 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 196 syntax errors.
	at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:154)
	at org.mozilla.javascript.Parser.parse(Parser.java:392)
	at org.mozilla.javascript.Parser.parse(Parser.java:337)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:312)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:533)
	at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)

**Comment by pmcquay** [comment]
hmm. Seems like its not "There is an invlid propery named "id"", but more "there is an invalid property identifier".

Something like this? https://github.com/yui/yuicompressor/issues/300 Not sure if this is actually the problem though.

**Comment by pmcquay** [comment]
ahh, looks like yui is choking on the usage of the keyword "default", at least for the first error here:

 this.config = (0, _config2.default)(config);

**Comment by schne324** [comment]
yea sorry about this. This relates to #17 . I just need to tag a release which I will do this evening

see: https://github.com/schne324/combobo/blob/master/package.json#L5

**Comment by schne324** [comment]
for now, you _should_ be able to `require('combobo/dist/combobo.js')` or if you're just dropping a script into a page use https://unpkg.com/combobo@1.1.1/dist/combobo.js

**Comment by pmcquay** [comment]
ah, actually we are already running the older script, and it still has errors. I tried the newer one hoping that it had fixed things, and that was the source of the errors I reported.

for instance: function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

**Comment by schne324** [comment]
this shouldn't be a problem anymore - just tagged version 2.0.0.

Let me know if you still have problems

**Comment by pmcquay** [comment]
this will still have problems. The Dist file has not been modified. I do not have the environment set up to compile this.

**Comment by schne324** [comment]
There is absolutely no need to compile this.  That's the point of the dist bundle.  This is likely something funky with your setup as I've just setup a codepen with a working combobo in about 2 minutes without any problems: https://codepen.io/schne324/pen/Yepdpd

(this is using the dist bundle: https://unpkg.com/combobo@2.0.0/dist/combobo.js)

**Comment by pmcquay** [comment]
The problem I am having is that when I try to minify the file you supply in the dist folder, my minifier reports errors. As far as I can tell the dist file has not changed, thus I will still get errors when my minifier tries to minify it.

**Comment by schne324** [comment]
I just tagged a patch release (2.0.1) in which the dist bundle is already minified. In addition, I just confirmed that a minifyer doesn't choke up on this (I used uglifyjs).
