### ISSUE TITLE
Non-editable, select-only combobox

### ISSUE THREAD

**Issue by LukaszJaro** [dequelabs/combobo#34]
Is it possible so there is non editable search input field and just functions like regular select box?

Here's a example https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/

**Comment by jesraygarciano** [comment]
@LukaszJaro so you mean just a regular Select box?

**Comment by LukaszJaro** [comment]
I can't recall why I asked that question, closed.
